export const CONTENT_KEY = {
    HOME: 'HOME',
    EX_PROPS: 'EX_PROPS',
    EX_INSTANCE_METHODS: 'EX_INSTANCE_METHODS',
    EX_CALLBACK_FUNCTIONS: 'EX_CALLBACK_FUNCTIONS',
    EX_EVENT_BUBBLING: 'EX_EVENT_BUBBLING',
    EX_PARENT_COMPONENT: 'EX_PARENT_COMPONENT',
    EX_OBSERVER_PATTERN: 'EX_OBSERVER_PATTERN',
    EX_GLOBAL_VARIABLES: 'EX_GLOBAL_VARIABLES',
    EX_CONTEXT: 'EX_CONTEXT'
}
